CoviDiscusion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('case/', include('case.urls')),
    path('experiences/', include('experiences.urls'))
]

case/urls.py
from django.urls import path

from . import views

app_name = 'case'

urlpatterns = [
    path('', views.case, name='case'),
    path('detail/<int:nomor>', views.detail, name='detail'),
]

experiences/urls.py
from django.urls import path

from .views import experiences, saveexperience, deleteexperience

app_name = 'experiences'

urlpatterns = [
    path('', experiences, name='experiences'),
    path('saveexperience', saveexperience, name='saveexperience' ),
    path('deleteexperience/<str:pk>', deleteexperience, name='deleteexperience'),
]

main/urls.py
from django.urls import path

from . import views
from .views import savesaran, deletesaran

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('savesaran', savesaran, name='savesaran'),
    path('deletesaran/<str:pk>', deletesaran, name='deletesaran'),
]

case/models.py
from django.db import models

class Kasus(models.Model):
	jumlah = models.PositiveIntegerField(default = 1)
	prov = models.CharField(max_length = 50, choices= [('Aceh', 'Aceh'), ('Bali', 'Bali'), ('Banten', 'Banten'), ('Bengkulu', 'Bengkulu'), ('DIY', 'DIY'), ('DKI Jakarta', 'DKI Jakarta'), ('Gorontalo', 'Gorontalo'), ('Jambi', 'Jambi'), ('Jabar', 'Jabar'), ('Jateng', 'Jateng'), ('Jatim', 'Jatim'), ('Kalbar', 'Kalbar'), ('Kalsel', 'Kalsel'), ('Kalteng', 'Kalteng'), ('Kaltim', 'Kaltim'), ('Kaltara', 'Kaltara'), ('Babel', 'Babel'), ('Kepri', 'Kepri'), ('Lampung', 'Lampung'), ('Maluku', 'Maluku'), ('Malut', 'Malut'), ('NTB', 'NTB'), ('NTT', 'NTT'), ('Papua', 'Papua'), ('Papbar', 'Papbar'), ('Riau', 'Riau'), ('Sulbar', 'Sulbar'), ('Sulsel', 'Sulsel'), ('Sulteng', 'Sulteng'), ('Sultara', 'Sultara'), ('Sulut', 'Sulut'), ('Sumbar', 'Sumbar'), ('Sumsel', 'Sumsel'), ('Sumut', 'Sumut')])
	kotkab = models.CharField(max_length = 50)

experiences/models.py
from django.db import models

# Create your models here.
class Experience(models.Model):
    nama = models.CharField(max_length = 50)
    lokasi = models.CharField(max_length = 100)
    pengalaman = models.TextField()

main/models.py
from django.db import models

class Saran(models.Model):
	nama = models.CharField(max_length=50)
	lokasi = models.CharField(max_length=50)
	saran = models.TextField()

case/forms.py
from django import forms
from .models import Kasus

class FormKasus(forms.ModelForm):
    class Meta:
        model = Kasus
        fields = "__all__"
        widgets = {
            'jumlah' : forms.NumberInput(attrs={'class': 'form-control'}),
            'prov' : forms.Select(attrs={'class': 'form-control'}),
            'kotkab' : forms.TextInput(attrs={'class': 'form-control'}),
        }

experiences/forms.py
from django import forms
from .models import Experience

class FormExperience(forms.ModelForm):
    class Meta:
        model = Experience
        fields = "__all__"
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
            'lokasi' : forms.TextInput(attrs={'class': 'form-control'}),
            'pengalaman' : forms.Textarea(attrs={'class': 'form-control'}),
        }

main/forms.py
from django import forms
from .models import Saran

class FormSaran(forms.ModelForm):
    class Meta:
        model = Saran
        fields = "__all__"
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
            'lokasi' : forms.TextInput(attrs={'class': 'form-control'}),
            'saran' : forms.Textarea(attrs={'class': 'form-control'}),
        }

case/views.py
from django.shortcuts import render, redirect
from .models import Kasus
from .forms import FormKasus

def case(request):
	form = FormKasus()
	if request.method == "POST":
		form = FormKasus(request.POST)
		if form.is_valid():
			form.save()
			return redirect('case:case')
	dct = {}
	prov_list = []
	prov_all = []
	kasus = Kasus.objects.all()
	for ks in kasus:
		if ks.prov in dct :
			dct[ks.prov] += ks.jumlah
		else : 
			dct[ks.prov] = ks.jumlah
			prov_list.append(ks.prov)	
	for prov in prov_list :
		tmp = []
		for ks in kasus:
			if ks.prov in prov:
				s = ' '.join(w.capitalize() for w in ks.kotkab.split())    	
				if not s in tmp:
					tmp.append(s)
		tmp2 = []
		tmp2.append(prov)
		tmp2.append(tmp)
		tmp2.append(dct[prov])
		prov_all.append(tmp2)
		for ks in kasus:
			if ks.prov in prov:
				tmp2.append(ks)
				break
	context = {'form' : form, 'prov_all' : prov_all}
	return render(request, 'case/case.html', context)

def detail(request, nomor):
	prov = Kasus.objects.get(id = nomor)
	kasus_all = Kasus.objects.all()
	dct = {}
	data = []
	jum = 0
	for ks in kasus_all:
		if ks.prov == prov.prov:
			jum += ks.jumlah
			s = ' '.join(w.capitalize() for w in ks.kotkab.split())    	
			if s in dct:
				dct[s] += ks.jumlah
			else:
				dct[s] = ks.jumlah
	data.append(['Kota/Kabupaten', 'Jumlah'])
	for ks in dct:
		data.append([ks, dct[ks]])
	context = {'prov': prov, 'data': data, 'jum': jum}
	return render(request, 'case/detail.html', context)

experiences/views.py
from django.shortcuts import render, redirect
from .forms import FormExperience
from .models import Experience

# Create your views here.
def experiences(request):
    return render(request, 'experiences/experiences.html', {'form' : FormExperience, 'experiences' : Experience.objects.all()})

def saveexperience(request): 
    experience = FormExperience(request.POST or None)
    if experience.is_valid() and request.method == 'POST':
        experience.save()
    
    return redirect('experiences:experiences')

def deleteexperience(request, pk):
    experience = Experience.objects.get(id=pk)
    if request.method == 'POST':
        experience.delete()

    return redirect('experiences:experiences')

main/views.py
from django.shortcuts import render, redirect
from .models import Saran
from .forms import FormSaran
def home(request):
    return render(request, 'main/home.html', {'form':FormSaran, 'saran':Saran.objects.all()})

def savesaran(request):
	saran = FormSaran(request.POST or None)
	if saran.is_valid() and request.method == 'POST':
		saran.save()
	return redirect('main:home')

def deletesaran(request, pk):
	saran = Saran.objects.get(id=pk)
	if request.method == 'POST':
		saran.delete()
	return redirect('main:home')

case/templates/case/case.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
	<title>Case</title>
{% endblock %}
{% block content %}
<div class="text-center">
	<h1>Yuk sampaikan update kasus di daerahmu</h1>
	<p>Sampaikan update kasus di daerahmu</p>
</div>
<div class="text-center">
	<a type="button" href="#sampaikan_disini" class="btn btn-light border border-dark btn-lg font-weight-bold">SAMPAIKAN DISINI</a>
</div>
</br>
</br>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-dark p-3" style="background: white">
				<h4 class="text-center pb-4">Daftar Lokasi:</h4>
				<div class="row row-cols-3 mx-2">
					{% for prov in prov_all %}
					<div class="col-6 col-md-4 p-2">
						<div class="card border-secondary">
							<div class="card-body">
								<h5 class = "text-center font-weight-bold"> 
									<a class="card-title text-center text-body" href = "{% url 'case:detail' prov.3.id %}">{{prov.0}} : {{prov.2}}</a>
								</h5>
								</br>
								{% for kotkab in prov.1 %}
									<h6>
										<li> {{kotkab}} </li>
									</h6>
								{% endfor %}
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
				<br>
				<li>Klik nama provinsi untuk melihat detail kasus
			</div>
		</div>
	</div>
</div>
</br>
</br>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-dark p-3" id="sampaikan_disini" style="background: white">
				<h4 class="text-center">SAMPAIKAN DISINI</h4>
				<form class = "ml-5 mr-5 mt-2 font-weight-bold py-4" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<label for="jumlah">Jumlah</label> {{form.jumlah}}
					</div>
					<div class="form-group">
						<label for="prov">Provinsi</label> {{form.prov}}
					</div>
					<div class="form-group">
						<label for="kotkab">Kota / Kabupaten</label> {{form.kotkab}}
					</div>
					<center class="pt-3">
						<a type="submit" data-toggle="modal" data-target="#exampleModal" class="btn btn-light border border-dark font-weight-bold">SAMPAIKAN</a>
					</center>
					<!-- Modal -->
					<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<h6 class="modal-title" id="exampleModalLabel">Peringatan</h6>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<h5 class="modal-title" id="exampleModalLabel">Apakah anda yakin data yang dimasukkan sudah benar?</h5>
								</div>
								<div class="modal-footer">
									<button type="submit" class="btn btn-light border border-dark font-weight-bold">Sudah</button>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

case/templates/case/detail.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
	<title>{{prov.prov}}</title>
{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-dark p-3" style="background: white">
				<div class="text-center">
					<h1>Sebaran kasus Provinsi {{prov.prov}}</h1>
					<h2>{{jum}} Kasus</h2>
				</div>
				<div id="piechart"></div>
			</div>
		</div>	
	</div>
</div>
</br>
<div class="text-center">
	<a type="button" href="{% url 'case:case' %}" class="btn btn-light border border-dark btn-lg font-weight-bold">Kembali</a>
	
</div>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> 

<script type="text/javascript">
	// Load google charts
	google.charts.load('current', {'packages':['corechart']});
	google.charts.setOnLoadCallback(drawChart);

	// Draw the chart and set the chart values
	function drawChart() {
	  var data = google.visualization.arrayToDataTable({{data|safe}});

	  // Optional; add a title and set the width and height of the charts
	  var options = {
	    'pieSliceText': 'value-and-percentage',
        'labels': 'none',
        'height': '500',
      };

	  // Display the chart inside the <div> element with id="piechart"
	  var chart = new google.visualization.PieChart(document.getElementById('piechart'));
	  chart.draw(data, options);
	}
</script>

{% endblock content %}

experiences/templates/experiences/experiences.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Share Experiences</title>
{% endblock %}

{% block content %}

<div class="container-fluid my-5 mx-auto text-center" style="max-width: 810px;">
    <h1>Yuk sampaikan pengalamanmu selama masa pandemi</h1>
    <h6 class="mt-4 mx-2 text-muted">Sampaikan pengalaman selama PJJ, WFH, SFH, atau pengalaman lainnya selama masa pandemi</h6>
</div>
<div class="text-center py-3">
	<a type="button" href="#sampaikan_disini" class="btn btn-light border border-secondary btn-lg font-weight-bold">SAMPAIKAN DISINI</a>
</div>

<div class="container-fluid my-5">
	<div class="row overflow-auto">
		<div class="col-md-8 offset-md-2 ">
            <div class="rounded-lg border border-secondary p-3"  style="background: white">
                {% if experiences %}
                <div class="container-fluid  overflow-auto" style="max-height: 450px;">
                    {% for pengalaman in experiences %}
                    <div class="card border-white">
                        <div class="card-body">
                          <h4 class="card-title">{{ pengalaman.nama}}</h5>
                          <p class="card-subtitle mb-3 text-muted">{{ pengalaman.lokasi }}</p>
                          <h5 class="card-text">{{ pengalaman.pengalaman }}</h5>
                          <button type="reset" class="btn float-right" data-toggle="modal" data-target="#exampleModal{{ pengalaman.id }}">
                            <img src="{% static 'img/trash.png' %}" width="20" height="20" alt="trash">
                          </button>
                        </div>
                        <hr class="mx-5 my-1">
                    </div>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal{{ pengalaman.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Peringatan</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                                <h4>Apakah anda ingin menghapus tanggapan ini?</h4>

                                <div class="card border-white">
                                    <div class="card-body">
                                      <h4 class="card-title">{{ pengalaman.nama}}</h5>
                                      <p class="card-subtitle mb-3 text-muted">{{ pengalaman.lokasi }}</p>
                                      <h5 class="card-text">{{ pengalaman.pengalaman }}</h5>
                                    </div>
                                </div>
                               
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                            <form class="text-center" action="{% url 'experiences:deleteexperience' pengalaman.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Hapus</button>
                            </form>

                            </div>
                        </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>
				{% endif %}
			</div>
		</div>
    </div>
</div>

<div class="container-fluid my-5" id="sampaikan_disini">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-secondary p-3" style="background: white">
				<h4 class="text-center">SAMPAIKAN DISINI</h4>
				<form class = "ml-5 mr-5 mt-2 font-weight-bold py-4" action="{% url 'experiences:saveexperience' %}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<label for="jumlah">Nama</label> {{form.nama}}
					</div>
					<div class="form-group">
						<label for="prov">Lokasi</label> {{form.lokasi}}
					</div>
					<div class="form-group">
						<label for="kotkab">Pengalaman kamu</label> {{form.pengalaman}}
					</div>
					<center class="pt-3">
						<a type="button" data-toggle="modal" data-target="#exampleModal" class="btn btn-light border border-dark font-weight-bold">SAMPAIKAN</a>
					</center>
					<!-- Modal -->
					<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<h6 class="modal-title" id="exampleModalLabel">Peringatan</h6>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<h5 class="modal-title" id="exampleModalLabel">Apakah anda yakin data yang dimasukkan sudah benar?</h5>
								</div>
								<div class="modal-footer">
									<button type="submit" class="btn btn-light border border-dark font-weight-bold">Sudah</button>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
    </div>
</div>

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>CoviDiscussion</title>
{% endblock meta %} {% block content %}
<div class="text-center">
    <h1>Selamat Datang di CoviDiscussion</h1>
    <p>Tempat untuk saling diskusi dan bercerita tentang COVID-19</p>
</div>

<div class="container-fluid">
    <div class="row my-5">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-dark p-3" style="background: white">
                <h4 class="text-center pb-4">APA ITU COVID -19</h4>
                <p class="text-center pl-3 pr-3">Virus Corona atau severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) adalah virus yang menyerang sistem pernapasan. Penyakit karena infeksi virus ini disebut COVID-19. Virus Corona bisa menyebabkan gangguan ringan pada sistem
                    pernapasan, infeksi paru-paru yang berat, hingga kematian.</p>
            </div>
        </div>
    </div>
    <div class="row my-5">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-dark p-3" style="background: white">
                <h4 class="text-center pb-4">PEYEBARAN COVID-19</h4>
                <p class="text-center pl-3 pr-3">Virus Corona atau severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) adalah virus yang menyerang sistem pernapasan. Penyakit karena infeksi virus ini disebut COVID-19. Virus Corona bisa menyebabkan gangguan ringan pada sistem
                    pernapasan, infeksi paru-paru yang berat, hingga kematian.</p>
            </div>
        </div>
    </div>
    <div class="row my-5">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-dark p-3" style="background: white">
                <h4 class="text-center pb-4">CARA PENCEGAHAN COVID-19</h4>
                <p class="pl-3 pr-3">Cara pencegahan Covid-19 :
                    <ol>
                        <li>Cuci tangan Anda secara rutin. Gunakan sabun dan air, atau cairan pembersih tangan berbahan alkohol.</li>
                        <li>Selalu jaga jarak aman dengan orang yang batuk atau bersin.</li>
                        <li>Kenakan masker jika pembatasan fisik tidak dimungkinkan.</li>
                        <li>Jangan sentuh mata, hidung, atau mulut Anda.</li>
                        <li>Saat batuk atau bersin, tutup mulut dan hidung Anda dengan lengan atau tisu.</li>
                        <li>Jangan keluar rumah jika merasa tidak enak badan.</li>
                        <li>Jika demam, batuk, atau kesulitan bernapas, segera cari bantuan medis.</li>
                    </ol>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid my-5">
    <div class="row overflow-auto">
        <div class="col-md-8 offset-md-2 ">
            <div class="rounded-lg border border-secondary p-3" style="background: white">
                {% if saran %}
                <div class="container-fluid  overflow-auto" style="height: 450px;">
                    {% for saran in saran %}
                    <div class="card border-white">
                        <div class="card-body">
                            <div style="display: inline-flex;">
                                <h4 class="card-title mr-4">{{ saran.nama}}</h4>
                                <p class="card-subtitle mt-1 text-muted">{{ saran.lokasi }}</p>
                            </div>
                            <h5 class="card-text">{{ saran.saran }}</h5>
                            <button type="reset" class="btn float-right" data-toggle="modal" data-target="#exampleModal{{ saran.id }}">
                            <img src="{% static 'img/trash.png' %}" width="20" height="20" alt="trash">
                          </button>
                        </div>
                        <hr class="mx-5">
                    </div>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal{{ saran.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Peringatan</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                                </div>
                                <div class="modal-body">
                                    <h4>Apakah anda ingin menghapus tanggapan ini?</h4>

                                    <div class="card border-white">
                                        <div class="card-body">
                                            <h4 class="card-title">{{ saran.nama}}</h5>
                                                <p class="card-subtitle mb-3 text-muted">{{ saran.lokasi }}</p>
                                                <h5 class="card-text">{{ saran.saran }}</h5>
                                        </div>
                                    </div>

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                                    <form class="text-center" action="{% url 'main:deletesaran' saran.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="container-fluid my-5" id="saran">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-secondary p-3" style="background: white">
                <h4 class="text-center">SARAN</h4>
                <form class="ml-5 mr-5 mt-2 font-weight-bold py-4" action="{% url 'main:savesaran' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="nama">Nama</label> {{form.nama}}
                    </div>
                    <div class="form-group">
                        <label for="lokasi">Lokasi</label> {{form.lokasi}}
                    </div>
                    <div class="form-group">
                        <label for="saran">Saran kamu</label> {{form.saran}}
                    </div>
                    <center class="pt-3">
                        <a type="button" data-toggle="modal" data-target="#exampleModal" class="btn btn-light border border-dark font-weight-bold">SAMPAIKAN</a>
                    </center>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h6 class="modal-title" id="exampleModalLabel">Peringatan</h6>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
                                </div>
                                <div class="modal-body">
                                    <h5 class="modal-title" id="exampleModalLabel">Apakah anda yakin data yang dimasukkan sudah benar?</h5>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-light border border-dark font-weight-bold">Sudah</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
<!doctype html> {%load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'logo.png' %}">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    {% block meta %} {% endblock %}
</head>

<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background: white">
        <a class="navbar-brand" href="{% url 'main:home' %}">
            <img src="{% static 'logo.png' %}" style="width:80px;height:80px;"> CoviDiscussion
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  			</button>
        <div class="collapse navbar-collapse navbar-right" id="navbarNavAltMarkup">
            <div class="navbar-nav navbar-right px-5 ml-auto">
                <a class="nav-item nav-link pr-5 h5" href="{% url 'main:home' %}">Covid-19</a>
                <a class="nav-item nav-link pr-5 h5" href="{% url 'case:case' %}">Case</a>
                <a class="nav-item nav-link pr-5 h5" href="{% url 'experiences:experiences' %}">Experiences</a>
            </div>
        </div>
    </nav>
    {% block content %} {% endblock %}
    </br>
    </br>
</body>

</html>